# Modeling data with numpy

In [1]:
import numpy as np

In [2]:
data=[1,2,3,4,5,6]

In [3]:
type(data)

list

Change the data to array structure.

In [4]:
arrayexample=np.array(data)

We look at the data type.

In [5]:
arrayexample.dtype

dtype('int32')

We change it to decimal.

In [6]:
arrayexample=np.array(data,dtype=float)

In [7]:
arrayexample.dtype

dtype('float64')

We look at the shape and dimension.

In [8]:
arrayexample.shape

(6,)

In [9]:
arrayexample.ndim

1

Let's create one of two dimensions.

In [10]:
data=[[1,2,3,4],[5,6,7,8]]
arrayexample=np.array(data)
arrayexample

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
arrayexample.shape

(2, 4)

In [12]:
arrayexample.ndim

2

# Creating a type of array


arange: array of the indicated order

ones: array composed of the number 1

zeros: array composed of the number 0

eye: array identity

In [13]:
arrayexample=np.arange(20)
arrayexample

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
arrayexample=np.arange(-1,1,0.5)
arrayexample

array([-1. , -0.5,  0. ,  0.5])

In [15]:
arrayexample=np.ones((3,2))
arrayexample

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
arrayexample=np.zeros((4,5,2))
arrayexample

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

Other ways of creating arrays

# Reshape & Flatten

In [17]:
arrayexample=np.ones(20).reshape(5,4)
arrayexample

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arrayexampleflatten=arrayexample.flatten()
arrayexampleflatten

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

# Linspace

In [19]:
arrayexample=np.linspace(1,10,100)
arrayexample

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

Vector that starts in 1 and finishes in 10, having 100 elements.

# Rand y Randn

In [20]:
arrayexample=np.random.rand(5)
arrayexample

array([0.34498155, 0.38080896, 0.39238899, 0.7079342 , 0.19239284])

In [21]:
arrayexample=np.random.randn(5)
arrayexample

array([0.80126564, 1.10800285, 2.90695723, 0.99497404, 0.03009861])

Rand lists random elements between 0 and 1.

Randn returns an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1.

# Transpose (or pivot)

In [22]:
arrayexample=np.arange(20).reshape(5,4)
arrayexample

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
arrayexampletr=arrayexample.transpose()
arrayexampletr

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Concatenate

In [24]:
arrayuno=np.ones(5)
arrayceros=np.zeros(5)

In [25]:
arrayconcat=np.concatenate((arrayuno,arrayceros))
arrayconcat

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0.])

In [26]:
arrayconcat=np.vstack((arrayuno,arrayceros))
arrayconcat

array([[1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

# Array operations

In [27]:
arrayexample=np.arange(8).reshape(2,4)
arrayexample

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [28]:
arraysum=arrayexample+arrayexample
arraysum

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [29]:
arraymult=arrayexample*arrayexample
arraymult

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

In [30]:
arraysumesc=arrayexample+1
arraysumesc

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
arraydiv=1/arraysumesc
arraydiv

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])

In [32]:
array2=arrayexample**2
array2

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]], dtype=int32)

# Indexing

In [33]:
arrayexample=np.arange(15)+1
arrayexample

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [34]:
arrayexample[4]

5

In [35]:
arrayexample[:3]

array([1, 2, 3])

In [36]:
arrayexample[-5:]

array([11, 12, 13, 14, 15])

In [37]:
arrayexample[4]=45
arrayexample

array([ 1,  2,  3,  4, 45,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
arrayexample[-1]

15

In [39]:
arrayexample=np.ones(6)
arrayexample

array([1., 1., 1., 1., 1., 1.])

In [40]:
arrayexamplesub=arrayexample[:2]
arrayexamplesub

array([1., 1.])

In [41]:
arrayexamplesub[:]=64
arrayexamplesub

array([64., 64.])

We can use ncopy to avoid that.

In [42]:
arrayexample=np.ones(6)
arrayexample

array([1., 1., 1., 1., 1., 1.])

In [43]:
arrayexamplesub=arrayexample[:2].copy()
arrayexamplesub

array([1., 1.])

In [44]:
arrayexamplesub[:]=64
arrayexamplesub

array([64., 64.])

In [45]:
arrayexample

array([1., 1., 1., 1., 1., 1.])

# Boolean Indexing

In [46]:
name=np.array(['juan','pepe','maria','ana'])

In [47]:
name.dtype

dtype('<U5')

String lower than 5 characters. 

In [48]:
datos=np.random.rand(4,3)
datos

array([[0.69623274, 0.05895226, 0.66722468],
       [0.74919426, 0.89828249, 0.70885555],
       [0.55385589, 0.11596271, 0.83140466],
       [0.60966934, 0.21591609, 0.4246087 ]])

In [49]:
name=='pepe'

array([False,  True, False, False])

In [50]:
datos[name=='pepe']

array([[0.74919426, 0.89828249, 0.70885555]])

In [51]:
datos[name=='pepe',2]

array([0.70885555])